from pydantic import BaseModel, Field
from typing import List, Dict, Optional


class Task(BaseModel):
    """
    Task used in training.
    """
    task_id: str = Field(default=...)

    env_type: str = Field(default="appworld")
    
    # whether this task is open query. open query has no clear stop condition.
    open_query: bool = Field() # FIXME debug, check if every instance handles this new attr. default False.

    metadata: dict = Field(default_factory=dict)
    
    # query. if set, the original query will be replaced by this before training.
    query: Optional[str] = Field(default=None) 
    
    # synthetic ground truth generated by TaskManager in stage 2, used in llm judge as reference trajectory
    ground_truth:Optional[str] = Field(default=None,description="ground truth")
    
    evaluator: str = Field(default="env")


class TaskObjective(BaseModel):
    """
    Task used in task exploration and extraction only.
    
    It includes the custom ground_truth and reward, which may be merged to Task and used in training in future.
    """
    
    task:Task=Field(...,description="task")
    confidence:Optional[float]=Field(None,description="confidence")
    reward:Optional[float]=Field(None,description="reward")
    
    @property
    def objective(self):
        return self.task.query
    
    @property
    def ground_truth(self):
        return self.task.ground_truth
    
    @ground_truth.setter
    def ground_truth(self,v):
        self.task.ground_truth=v